baseurl: accessible-switches
description: A collection of accessible switch technology
email: caos@googlegroups.com
github_username: a11yhood
plugins:
- jekyll-feed
- jekyll-octicons
- jekyll-readme-index
readme_index:
  enabled: true
  with_frontmatter: true
theme: minima
title: Accessible switches
url: https://a11yhood.org/accessible-switches
